AP photogram industrial 2
APatel-AI/photogram-industrial pull request #2
Opened 2024-07-01 19:54 UTC by APatel-AI

- Generated and migrated Comments, Follow Requests, and Likes tables using scaffold
- updated route connections

2024-07-01 21:23 UTC, thierrychau commented
For future reference: please only tag for a review once it ready. I see you are still committing to this, so not sure when it's ready for review.

Drop a comment here when it is.

2024-07-02 01:11 UTC, APatel-AI commented
Ready for review

2024-07-02 14:15 UTC, MayaS1111 commented
Looks good to me, let's see what Thierry is going to say

2024-07-02 14:16 UTC, MayaS1111 approved these changes
Looks good to me, let's see what Thierry is going to say

2024-07-02 15:49 UTC, thierrychau requested changes
Hi Arpan, great job so far. I have a few minor comments, please see below. Thanks!

2024-07-02 15:49 UTC, thierrychau commented on app/models/like.rb
> +  validates :user_id, uniqueness: { scope: :photo_id, message: "has already liked this photo" }
@APatel-AI you have a validation on a field named `user_id`, but in your like model you do not have this field. Can you update this?

2024-07-02 15:49 UTC, thierrychau commented on app/models/user.rb
> +  has_many :sent_follow_requests, foreign_key: :sender_id, class_name: "FollowRequest"
Can you add a `dependent: :destroy` to handle orphan records?

2024-07-02 17:02 UTC, APatel-AI commented
added dependent: :destroy to handle orphan records and updated the validation for like model

2024-07-02 17:13 UTC, dylansarikas approved these changes
Looks good Arpan!!  Neat and easy to follow.

2024-07-02 18:22 UTC, thierrychau approved these changes
Great job, good to merge. Thanks for the edits.

2024-07-02 18:26 UTC, merged